spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/net_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:net_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:net_password}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.initialization-mode=never

spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:guest}