spring.application.name=instance-service
server.port=8081
spring.datasource.url=jdbc:mysql://mysql-instances:3306/instances_db
spring.datasource.username=user_instances
spring.datasource.password=passwordinstances
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true

